### ISSUE TITLE
Failed to install in Raspberry Pi

### ISSUE THREAD

**Issue by efung1232** [Schlaubischlump/shairport-metadatareader-python#4]
My OS : Linux  5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
pip install git+https://github.com/htruong/shairport-metadatareader-python --> failed
I have installed the required python packages suggested in the Readme file. I have no idea what caused this problem.
python -V => Python 2.7.16,   pip 20.3.4 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
Here is the last few lines of the stack trace:
File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 44, in _execfile
        code = compile(script, filename, 'exec')
      File "/tmp/easy_install-92mtR7/pytest-runner-5.3.1/temp/easy_install-cJs6iC/setuptools_scm-6.3.2/setup.py", line 22
        f"{type(self).__name__} is forbidden, "
                                                                   ^
    SyntaxError: invalid syntax

**Comment by Schlaubischlump** [comment]
`pytest-runner-5.3.1/` seems to be >= python3.6 only. You need to install an older version with pip which supports python2, since you are trying to install `shairport-metadatareader-python` for python2 and not python3.

The better solution would be to upgrade your python installation on your raspberry pi to at least python3.6. Python2 reached its end of life in 2020, if I recall correctly.
